# Image: tapis/dyntapy
# Build: docker build -t tapis/dynatapy -f Dockerfile-dyna .
# Try it: docker run -it --network tenants-api_tenants --rm tapis/dynatapy bash

from tapis/flaskbase

USER root
ADD tapy/dyna/requirements.txt /home/tapis/requirements.txt
RUN pip install -r /home/tapis/requirements.txt

ADD tapy /home/tapis/tapy

RUN chown -R tapis:tapis /home/tapis
USER tapis
