# coding: utf-8

# flake8: noqa
"""
    Tenants API

    Manage Tapis Tenants.  # noqa: E501

    The version of the OpenAPI document: 1
    Contact: cicsupport@tacc.utexas.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from tenants.openapi_client.models.array_of_lda_ps import ArrayOfLDAPs
from tenants.openapi_client.models.array_of_owners import ArrayOfOwners
from tenants.openapi_client.models.array_of_tenants import ArrayOfTenants
from tenants.openapi_client.models.basic_response import BasicResponse
from tenants.openapi_client.models.inline_object import InlineObject
from tenants.openapi_client.models.inline_object1 import InlineObject1
from tenants.openapi_client.models.inline_object2 import InlineObject2
from tenants.openapi_client.models.ldap import LDAP
from tenants.openapi_client.models.new_ldap import NewLDAP
from tenants.openapi_client.models.new_tenant import NewTenant
from tenants.openapi_client.models.owner import Owner
from tenants.openapi_client.models.tenant import Tenant
