import openapi_client

class TenantsFactory(object):
    """
    Wrapper class for the autogenerated openapi client.
    """

    def __init__(self, config):
        # create a TenantsApi instance...
        configuration = openapi_client.Configuration()
        # tenants_client.TokensApi(config)
        pass
